//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public string ChatContent { get; set; }
        public System.DateTime ChatCreatTime { get; set; }
        public int MembersId { get; set; }
        public int SendMemId { get; set; }
        public int ChatStatus { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
