//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Color = new HashSet<Color>();
            this.Festival = new HashSet<Festival>();
            this.FlowerKind = new HashSet<FlowerKind>();
        }
    
        public int ClassId { get; set; }
        public string ClassName { get; set; }
    
        public virtual ICollection<Color> Color { get; set; }
        public virtual ICollection<Festival> Festival { get; set; }
        public virtual ICollection<FlowerKind> FlowerKind { get; set; }
    }
}
