//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowersSIMEntities : DbContext
    {
        public FlowersSIMEntities()
            : base("name=FlowersSIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admins> Admins { get; set; }
        public DbSet<Chat> Chat { get; set; }
        public DbSet<Class> Class { get; set; }
        public DbSet<Color> Color { get; set; }
        public DbSet<Festival> Festival { get; set; }
        public DbSet<FlowerKind> FlowerKind { get; set; }
        public DbSet<Members> Members { get; set; }
        public DbSet<OrderGoods> OrderGoods { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ShoppingCar> ShoppingCar { get; set; }
    }
}
