//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowerKind
    {
        public FlowerKind()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int FlowerKindId { get; set; }
        public string FlowerKindName { get; set; }
        public int ClassId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
