//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.Chat = new HashSet<Chat>();
            this.Orders = new HashSet<Orders>();
            this.ShoppingCar = new HashSet<ShoppingCar>();
        }
    
        public int MembersId { get; set; }
        public string MembersName { get; set; }
        public string MembersPwd { get; set; }
        public int Gender { get; set; }
        public string Phone { get; set; }
        public int LoginStatus { get; set; }
    
        public virtual ICollection<Chat> Chat { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ShoppingCar> ShoppingCar { get; set; }
    }
}
