//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderGoods
    {
        public int OGId { get; set; }
        public string ProductName { get; set; }
        public string Picture1 { get; set; }
        public Nullable<decimal> NowPrice { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
