//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrdersId { get; set; }
        public int MembersId { get; set; }
        public string OrdersName { get; set; }
        public string OrdersPhone { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneeAddress { get; set; }
        public int carOrproduct { get; set; }
        public string ProductIdList { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public decimal Price { get; set; }
        public int Status { get; set; }
        public string OrderNumbers { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
