//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ShoppingCar = new HashSet<ShoppingCar>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int ProductVolume { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string Picture3 { get; set; }
        public string Picture4 { get; set; }
        public string Picture5 { get; set; }
        public string Material { get; set; }
        public string Package { get; set; }
        public string FlowerLanguage { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public decimal NowPrice { get; set; }
        public int Inventory { get; set; }
        public int FestivalId { get; set; }
        public int ColorId { get; set; }
        public int FlowerKindId { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Festival Festival { get; set; }
        public virtual FlowerKind FlowerKind { get; set; }
        public virtual ICollection<ShoppingCar> ShoppingCar { get; set; }
    }
}
